version: '3.7'

services:
  mysql-hive:
    image: hypriot/rpi-mysql:latest
    networks: 
      - spark
    environment: 
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3307:3306"
    volumes:
      - "./db/mysql/dump/hive/1.2.2:/docker-entrypoint-initdb.d"

  mysql-dw:
    image: hypriot/rpi-mysql:latest
    networks: 
      - spark
    environment: 
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"
    volumes:
      - "./db/mysql/dump/foodmart:/docker-entrypoint-initdb.d"

  spark-master:
    image: jsminet/docker-apache-spark:2.4.8
    networks: 
      - spark
    deploy:
      placement:
        constraints: [node.role == manager]
    environment: 
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
      - "SPARK_CONF_DIR=/app/spark/conf"
      - "SPARK_LOG_DIR=/app/spark/logs/master"
    ports:
      - "8080:8080"
    volumes:
      - "./app/spark:/app/spark"

  spark-worker:
    image: jsminet/docker-apache-spark:2.4.8
    networks: 
      - spark
    environment: 
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=8g"
      - "SPARK_CONF_DIR=/app/spark/conf"
      - "SPARK_LOG_DIR=/app/spark/logs/worker1"
      - "SPARK_WORKER_DIR=/app/spark/work/worker1"
    ports:
      - "8081:8081"
    depends_on: 
      - spark-master
    command: worker spark://spark-master:7077
    volumes:
      - "./app/spark:/app/spark"

  thriftserver:
    image: jsminet/docker-apache-spark:2.4.8
    networks: 
      - spark
    environment: 
      - "HIVE_SERVER2_THRIFT_PORT=10000"
      - "SPARK_CONF_DIR=/app/spark/conf"
    ports:
      - "10000:10000"
    depends_on: 
      - spark-worker
      - mysql-hive
    command: thriftserver --master spark://spark-master:7077 --verbose
    volumes:
      - "./app/spark:/app/spark"

  adminer:
    image: adminer:latest
    networks: 
      - spark
    deploy:
      placement:
        constraints: [node.role == manager]
    restart: always
    ports:
        - 7080:8080

networks:
  spark:
    external: true