version: '3.7'

services:
  mysql-hive:
    image: mysql:5.7.33
    environment: 
      - "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD"
    ports:
      - "3307:3306"
    volumes:
      - "./db/mysql/dump/hive/2.3.9:/docker-entrypoint-initdb.d"

  mysql-dw:
    image: mysql:5.7.33
    environment: 
      - "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD"
    ports:
      - "3306:3306"
    volumes:
      - "./db/mysql/dump/foodmart:/docker-entrypoint-initdb.d"

  spark-master:
    image: ${SPARK_IMAGE}
    environment: 
      - "SPARK_MASTER_PORT=$SPARK_MASTER_PORT"
      - "SPARK_MASTER_WEBUI_PORT=$SPARK_MASTER_WEBUI_PORT"
      - "SPARK_CONF_DIR=$SPARK_CONF_DIR"
      - "SPARK_LOG_DIR=$SPARK_LOG_DIR/master"
    ports:
      - "$SPARK_MASTER_WEBUI_PORT:$SPARK_MASTER_WEBUI_PORT"
    volumes:
      - "./app/spark:/app/spark"

  spark-worker-1:
    image: ${SPARK_IMAGE}
    environment: 
      - "SPARK_WORKER_CORES=$SPARK_WORKER_CORES"
      - "SPARK_WORKER_MEMORY=$SPARK_WORKER_MEMORY"
      - "SPARK_CONF_DIR=$SPARK_CONF_DIR"
      - "SPARK_LOG_DIR=$SPARK_LOG_DIR/worker1"
      - "SPARK_WORKER_DIR=$SPARK_WORKER_DIR/worker1"
    ports:
      - "8081:8081"
    depends_on: 
      - spark-master
    command: worker spark://spark-master:$SPARK_MASTER_PORT
    volumes:
      - "./app/spark:/app/spark"
      - "./drivers/mysql:/drivers/mysql"

  zeppelin:
    image: apache/zeppelin:0.10.0
    environment:
      - "SPARK_MASTER=spark://spark-master:$SPARK_MASTER_PORT"
      - "SPARK_HOME=/opt/spark"
      - "ZEPPELIN_CONF_DIR=$ZEPPELIN_CONF_DIR"
      - "ZEPPELIN_LOG_DIR=$ZEPPELIN_LOG_DIR"
      - "ZEPPELIN_NOTEBOOK_DIR=$ZEPPELIN_NOTEBOOK_DIR"
    ports:
      - "9080:8080"
    volumes:
      - "./app/zeppelin:/app/zeppelin"
      - "spark3:/opt/spark"

  adminer:
    image: adminer:latest
    restart: always
    ports:
        - 7080:8080

volumes: 
  spark3: